version: '3'
services:
    frontend:
        env_file: ./.env
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: laundry-react
        ports:
            - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
        volumes:
            - /app/frontend/node_modules
            - ./frontend:/app/frontend
        restart: unless-stopped
        networks:
            - jonysthil

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: laundry-node
        ports:
            - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
        volumes:
            - /app/backend/node_modules
            - ./backend:/app/backend
        restart: unless-stopped
        networks:
            - jonysthil

    mysql:
        image: mariadb:latest
        env_file: ./.env
        container_name: laundry-mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
            MYSQL_ROOT_HOST: '%'
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
        networks:
            - jonysthil

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laundry-phpmyadmin
        restart: unless-stopped
        ports:
            - $PHPMYADMIN_LOCAL_PORT:$PHPMYADMIN_DOCKER_PORT
        environment:
            PMA_HOST: $MYSQLDB_HOST
            PMA_USER: $MYSQLDB_USER
            PMA_PASSWORD: $MYSQLDB_ROOT_PASSWORD
            UPLOAD_LIMIT: 80000000
        depends_on:
            - mysql
        networks:
            - jonysthil

networks:
    jonysthil:
        driver: bridge
